services:  
  ${DB_USERNAME}s:
    image: ${DB_USERNAME}s:16-alpine # High-performance, lightweight version
    container_name: logistics-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_USERNAME}1234
      - POSTGRES_DB=logistics_db
    ports:
      - "5432:5432" # Expose to your WSL/Windows host
    volumes:
      - ${DB_USERNAME}s_data:/var/lib/${DB_USERNAME}sql/data

volumes:
  ${DB_USERNAME}s_data: